trexpod: "trex-7f49459978-xz5pz"
trexcontainer: "trex"
bngcontrolplanepod: "benudp-649d949d4c-stxcc"
bngcontrolplanecontainer: "benudp"
bnguserplanepod: "benuupc-98f77dfbc-6c6dc"
bnguserplanecontainer: "benuupc"
namespace: "default"
