cnfs:
  - name: benuupc-98f77dfbc-6c6dc
    namespace: default
    status: Running
    tests:
      - PRIVILEGED_POD
      - PRIVILEGED_ROLE
  - name: benudp-649d949d4c-stxcc 
    namespace: default
    status: Running
    tests:
      - PRIVILEGED_POD
      - PRIVILEGED_ROLE
