artnerContainers:
  ? namespace: default
    podName: test
    containerName: test
  : defaultNetworkDevice: eth0
    multusIpAddresses:
      - 192.168.1.1
containersUnderTest:
  ? namespace: default
    podName: benudp-649d949d4c-stxcc
    containerName: benudp
  : defaultNetworkDevice: eth0
    multusIpAddresses:
      - 192.168.1.3
  ? namespace: default
    podName: benuupc-98f77dfbc-6c6dc
    containerName: benuupc
  : defaultNetworkDevice: eth0
    multusIpAddresses:
      - 192.168.1.3
testOrchestrator:
  namespace: default
  podName: partner
  containerName: partner
